export {
  buildProjectGroups,
  buildProjectSpaceSections,
  listProjectSpaceNames,
  resolveProjectGroupSpace,
  UNSPACED_PROJECT_SECTION_KEY,
  deriveLogicalProjectKey,
  deriveLogicalProjectKeyFromSettings,
  derivePhysicalProjectKey,
  derivePhysicalProjectKeyFromPath,
  deriveProjectGroupingOverrideKey,
  getProjectOrderKey,
  resolveProjectGroupingMode,
  selectProjectGroupingSettings,
  type ProjectGroupingMode,
  type ProjectGroupingSettings,
  type ProjectGroup,
  type ProjectGroupMember,
  type ProjectSpaceSection,
} from "@t3tools/client-runtime/state/project-grouping";
